class Translator {
  static String currentLang = 'en';

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'FixCity',
      'report_issue': 'Report Issue',
      'dashboard': 'Dashboard',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'desc_hint': 'Describe the issue...',
      'submit': 'Submit Report',
      'admin_actions': 'Admin Actions',
      'status_updated': 'Status Updated',
      'print_pdf': 'Print Official Work Order',
      'ai_assessment': 'AI Assessment',
      'cost_estimation': 'Cost & Resource Estimation',
      'est_budget': 'Est. Budget',
      'labor_req': 'Labor Req.',
      'materials': 'Materials Needed:',
      'humanitarian_alert': 'Humanitarian Alert',
      'help_required': 'Community help required.',
      'location_context': 'Location Context',
      'view_as': 'View As',
      'logout': 'Log Out',
      'home': 'Home',
      'profile': 'My Profile',
      'login': 'Log In',
      'signup': 'Sign Up',
      'or': 'OR',
      'continue_google': 'Continue with Google',
    },
    'ta': {
      // Tamil
      'app_title': 'பிக்ஸ் சிட்டி',
      'report_issue': 'புகார் அளிக்கவும்',
      'dashboard': 'நிர்வாக பலகை',
      'camera': 'கேமரா',
      'gallery': 'கேலரி',
      'desc_hint': 'பிரச்சினையை விவரிக்கவும்...',
      'submit': 'சமர்ப்பிக்கவும்',
      'admin_actions': 'நிர்வாக நடவடிக்கைகள்',
      'status_updated': 'நிலை புதுப்பிக்கப்பட்டது',
      'print_pdf': 'அதிகாரப்பூர்வ ஆணை அச்சிடுக',
      'ai_assessment': 'AI மதிப்பீடு',
      'cost_estimation': 'செலவு மற்றும் வள மதிப்பீடு',
      'est_budget': 'மதிப்பிடப்பட்ட பட்ஜெட்',
      'labor_req': 'தேவையான பணியாளர்கள்',
      'materials': 'தேவையான பொருட்கள்:',
      'humanitarian_alert': 'மனிதாபிமான எச்சரிக்கை',
      'help_required': 'சமூக உதவி தேவை.',
      'location_context': 'இட விவரம்',
      'view_as': 'பார்வை:',
      'logout': 'வெளியேறு',
      'home': 'முகப்பு',
      'profile': 'என் விவரம்',
      'login': 'உள்நுழைக',
      'signup': 'பதிவு செய்க',
      'or': 'அல்லது',
      'continue_google': 'கூகிள் மூலம் தொடரவும்',
    },
    'hi': {
      // Hindi
      'app_title': 'फिक्स सिटी',
      'report_issue': 'समस्या रिपोर्ट करें',
      'dashboard': 'डैशबोर्ड',
      'camera': 'कैमरा',
      'gallery': 'गैलरी',
      'desc_hint': 'समस्या का वर्णन करें...',
      'submit': 'जमा करें',
      'admin_actions': 'प्रशासनिक कार्य',
      'status_updated': 'स्थिति अपडेट की गई',
      'print_pdf': 'आधिकारिक आदेश प्रिंट करें',
      'ai_assessment': 'AI मूल्यांकन',
      'cost_estimation': 'लागत और संसाधन अनुमान',
      'est_budget': 'अनुमानित बजट',
      'labor_req': 'आवश्यक श्रम',
      'materials': 'आवश्यक सामग्री:',
      'humanitarian_alert': 'मानवीय चेतावनी',
      'help_required': 'सामुदायिक मदद की आवश्यकता है।',
      'location_context': 'स्थान संदर्भ',
      'view_as': 'के रूप में देखें',
      'logout': 'लॉग आउट',
      'home': 'होम',
      'profile': 'मेरी प्रोफाइल',
      'login': 'लॉग इन करें',
      'signup': 'साइन अप करें',
      'or': 'या',
      'continue_google': 'गूगल के साथ जारी रखें',
    },
  };

  static String t(String key) {
    return _localizedValues[currentLang]?[key] ?? key;
  }
}
